server:
  address: localhost:8080

auth:
  foo:
    type: basic
    username: foo
    password: bar
  bar:
    type: bearer
    token: bar

hooks:
  hello/world:
    command: "bash"
    args:
      - ./test.sh
    auth:
      - foo
      - bar

  hello/hell:
    command: "bash"
    args:
      - "hello world"
    auth:
      - bar
