name: Docker Release

# src: https://docs.docker.com/build/ci/github-actions/multi-platform/

on:
  workflow_dispatch:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: zekrotja/webhook

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long,enable=${{ github.ref_type != 'tag' }}
            type=ref,event=branch
            type=semver,pattern={{raw}},enable=${{ github.ref_type == 'tag' }}
            type=raw,value=latest,enable=${{ github.event.ref =='refs/heads/main'}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
